/directories/services/list:
  post:
    tags: [Services]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/directories/ServiceFilters.yaml"
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/directories/ServiceRowApiResponse.yaml"
      '401':
        $ref: "../../components/responses/Unauthorized.yaml"
/directories/services/list/nextpage:
  post:
    tags: [Services]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/_shared/NextPageRequest.yaml"
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/directories/ServiceRowApiResponse.yaml"
      '401':
        $ref: "../../components/responses/Unauthorized.yaml"
/directories/services:
  post:
    tags: [Services]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/directories/Service.yaml"
    responses:
      '201':
        description: Created
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/directories/Service.yaml"
      '401':
        $ref: "../../components/responses/Unauthorized.yaml"
